/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUmVwb3MvZWxlY3Ryb24vZWxlY3Ryb24tYW5ndWxhci9lbGVjdHJvbi1hbmd1bGFyL3NyYy9hcHAvdGl0bGUtYmFyL3RpdGxlLWJhci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1JlcG9zL2VsZWN0cm9uL2VsZWN0cm9uLWFuZ3VsYXIvZWxlY3Ryb24tYW5ndWxhci9zcmMvYXBwL3RpdGxlLWJhci90aXRsZS1iYXIuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
