/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './electron-info.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../../../../src/app/electron-info/electron-info.component';
const styles_ElectronInfoComponent:any[] = [i0.styles];
export const RenderType_ElectronInfoComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_ElectronInfoComponent,data:{}});
export function View_ElectronInfoComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['We are using node ',',\nChrome ',',\nand Electron ',
          '.']))],(null as any),(_ck,_v) => {
    var _co:i2.ElectronInfoComponent = _v.component;
    const currVal_0:any = _co.process.versions.node;
    const currVal_1:any = _co.process.versions.chrome;
    const currVal_2:any = _co.process.versions.electron;
    _ck(_v,1,0,currVal_0,currVal_1,currVal_2);
  });
}
export function View_ElectronInfoComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'electron-info',
      ([] as any[]),(null as any),(null as any),(null as any),View_ElectronInfoComponent_0,
      RenderType_ElectronInfoComponent)),i1.ɵdid(49152,(null as any),0,i2.ElectronInfoComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ElectronInfoComponentNgFactory:i1.ComponentFactory<i2.ElectronInfoComponent> = i1.ɵccf('electron-info',
    i2.ElectronInfoComponent,View_ElectronInfoComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUmVwb3MvZWxlY3Ryb24vZWxlY3Ryb24tYW5ndWxhci9lbGVjdHJvbi1hbmd1bGFyL3NyYy9hcHAvZWxlY3Ryb24taW5mby9lbGVjdHJvbi1pbmZvLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9SZXBvcy9lbGVjdHJvbi9lbGVjdHJvbi1hbmd1bGFyL2VsZWN0cm9uLWFuZ3VsYXIvc3JjL2FwcC9lbGVjdHJvbi1pbmZvL2VsZWN0cm9uLWluZm8uY29tcG9uZW50LnRzIiwibmc6Ly8vQzovUmVwb3MvZWxlY3Ryb24vZWxlY3Ryb24tYW5ndWxhci9lbGVjdHJvbi1hbmd1bGFyL3NyYy9hcHAvZWxlY3Ryb24taW5mby9lbGVjdHJvbi1pbmZvLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovUmVwb3MvZWxlY3Ryb24vZWxlY3Ryb24tYW5ndWxhci9lbGVjdHJvbi1hbmd1bGFyL3NyYy9hcHAvZWxlY3Ryb24taW5mby9lbGVjdHJvbi1pbmZvLmNvbXBvbmVudC50cy5FbGVjdHJvbkluZm9Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8cD5XZSBhcmUgdXNpbmcgbm9kZSB7e3Byb2Nlc3MudmVyc2lvbnMubm9kZX19LFxyXG5DaHJvbWUge3twcm9jZXNzLnZlcnNpb25zLmNocm9tZX19LFxyXG5hbmQgRWxlY3Ryb24ge3twcm9jZXNzLnZlcnNpb25zLmVsZWN0cm9ufX0uPC9wPiIsIjxlbGVjdHJvbi1pbmZvPjwvZWxlY3Ryb24taW5mbz4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQSx3RUFBRzthQUFBO1VBQUE7O0lBQUE7SUFBQTtJQUFBO0lBQUE7Ozs7b0JDQUg7TUFBQTtzQ0FBQSxVQUFBO01BQUE7OzsifQ==
